services:
  app:
    build: .
    container_name: mern_ecommerce_app
    ports:
      - "4001:4000"
    environment:
      - DB_URI=mongodb://mongo:27017/ecommerce 
      - PORT=4000
      - JWT_SECRET=5ygV>@]K-H(#\nP*$5;.H6{|v<bzsn6Vwe`EQ3)T8mvK6(x2F9
      - JWT_EXPIRE=5d
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    depends_on:
      mongo:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: my_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: my_elasticsearch
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped

volumes:
  mongo-data:
    driver: local
  elasticsearch-data:
    driver: local