export const ANALYTICS_REQUEST = 'ANALYTICS_REQUEST';
export const ANALYTICS_SUCCESS = 'ANALYTICS_SUCCESS';
export const ANALYTICS_FAIL = 'ANALYTICS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
