export const ANALYTICS_REQUEST = 'ANALYTICS_REQUEST';
export const ANALYTICS_SUCCESS = 'ANALYTICS_SUCCESS';
export const ANALYTICS_FAIL = 'ANALYTICS_FAIL';

export const ADMIN_STATS_REQUEST = 'ADMIN_STATS_REQUEST';
export const ADMIN_STATS_SUCCESS = 'ADMIN_STATS_SUCCESS';
export const ADMIN_STATS_FAIL = 'ADMIN_STATS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
