export const CONTACT_REQUEST = 'CONTACT_REQUEST';
export const CONTACT_SUCCESS = 'CONTACT_SUCCESS';
export const CONTACT_FAIL = 'CONTACT_FAIL';

export const CLEAR_CONTACT = 'CLEAR_CONTACT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
