export const GENERATE_COUPON_REQUEST = 'GENERATE_COUPON_REQUEST';
export const GENERATE_COUPON_SUCCESS = 'GENERATE_COUPON_SUCCESS';
export const GENERATE_COUPON_FAIL = 'GENERATE_COUPON_FAIL';

export const FETCH_COUPONS_REQUEST = 'FETCH_COUPONS_REQUEST';
export const FETCH_COUPONS_SUCCESS = 'FETCH_COUPONS_SUCCESS';
export const FETCH_COUPONS_FAIL = 'FETCH_COUPONS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
