export const SUBSCRIBE_REQUEST = 'SUBSCRIBE_REQUEST';
export const SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS';
export const SUBSCRIBE_FAIL = 'SUBSCRIBE_FAIL';

export const CLEAR_SUBSCRIBE = 'CLEAR_SUBSCRIBE';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
