export const ALL_PRICES_REQUEST = 'ALL_PRICES_REQUEST';
export const ALL_PRICES_SUCCESS = 'ALL_PRICES_SUCCESS';
export const ALL_PRICES_FAIL = 'ALL_PRICES_FAIL';

export const CREATE_SUBSCRIPTION_REQUEST = 'CREATE_SUBSCRIPTION_REQUEST';
export const CREATE_SUBSCRIPTION_SUCCESS = 'CREATE_SUBSCRIPTION_SUCCESS';
export const CREATE_SUBSCRIPTION_FAIL = 'CREATE_SUBSCRIPTION_FAIL';

export const SUBSCRIPTION_REQUEST = 'SUBSCRIPTION_REQUEST';
export const SUBSCRIPTION_SUCCESS = 'SUBSCRIPTION_SUCCESS';
export const SUBSCRIPTION_FAIL = 'SUBSCRIPTION_FAIL';

export const GET_SUBSCRIPTION_DETAIL_REQUEST =
    'GET_SUBSCRIPTION_DETAIL_REQUEST';
export const GET_SUBSCRIPTION_DETAIL_SUCCESS =
    'GET_SUBSCRIPTION_DETAIL_SUCCESS';
export const GET_SUBSCRIPTION_DETAIL_FAIL = 'GET_SUBSCRIPTION_DETAIL_FAIL';

export const UPDATE_SUBSCRIPTION_REQUEST = 'UPDATE_SUBSCRIPTION_REQUEST';
export const UPDATE_SUBSCRIPTION_SUCCESS = 'UPDATE_SUBSCRIPTION_SUCCESS';
export const UPDATE_SUBSCRIPTION_FAIL = 'UPDATE_SUBSCRIPTION_FAIL';

export const CANCEL_SUBSCRIPTION_REQUEST = 'CANCEL_SUBSCRIPTION_REQUEST';
export const CANCEL_SUBSCRIPTION_SUCCESS = 'CANCEL_SUBSCRIPTION_SUCCESS';
export const CANCEL_SUBSCRIPTION_FAIL = 'CANCEL_SUBSCRIPTION_FAIL';

export const DELETE_SUBSCRIPTION_REQUEST = 'DELETE_SUBSCRIPTION_REQUEST';
export const DELETE_SUBSCRIPTION_SUCCESS = 'DELETE_SUBSCRIPTION_SUCCESS';
export const DELETE_SUBSCRIPTION_FAIL = 'DELETE_SUBSCRIPTION_FAIL';

export const CLEAR_SUBSCRIPTION = 'CLEAR_SUBSCRIPTION';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
